sudo: required
services:
    - docker

before_install:
    - docker build -t talalkhilji/docker-react -f Dockerfile .

script:
    - docker run -e CI=true talalkhilji/docker-react

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-314978137134"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY