# Use an existing image as a base
FROM node:alpine

WORKDIR /app
# Download and install a dependency
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Tell the image what todo what it starts
# as a container
CMD ["npm","run","start"]
EXPOSE 80